version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
    patterns: ['*']
    cooldown:
      default-days: 2
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '17:00'
      timezone: 'America/Chicago'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      all-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      all-dependencies:
        patterns:
          - '*'
