allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
  workerd: true
overrides:
  cookie: ^1.1.1
  devalue: ^5.6.2
  undici: ^7.18.2
  rollup: '>=4.59.0'
  ws: '>=8.21.0'
  sharp: '0.34.5'
  vite@*: 'catalog:'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-core@0.2.9'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.2.9'
  - '@voidzero-dev/vite-plus-darwin-x64@0.2.9'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.9'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.2.9'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.2.9'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.2.9'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.9'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.2.9'
  - vite-plus@0.2.9
  - '@sveltejs/enhanced-img@1.0.0-next.5'
