allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
  workerd: true
overrides:
  cookie: ^1.1.1
  devalue: ^5.6.2
  undici: ^7.18.2
  rollup: '>=4.59.0'
  vite: 'catalog:'
  ws: '>=8.21.0'
  sharp: '0.34.5'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: ^0.2.8
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
minimumReleaseAgeExclude:
  - '@sveltejs/adapter-static@4.0.0-next.3'
  - '@sveltejs/kit@3.0.0-next.14'
