// This file is generated by Velite

export { default as indexPage } from './indexPage.json'
export { default as setup } from './setup.json'
export { default as configuration } from './configuration.json'
export { default as userManagement } from './userManagement.json'
export { default as features } from './features.json'
export { default as guides } from './guides.json'
export { default as development } from './development.json'
export { default as templates } from './templates.json'