// This file is generated by Velite

import type __vc from '../velite.config.js'

type Collections = typeof __vc.collections

export type indexPage = Collections['indexPage']['schema']['_output']
export declare const indexPage: indexPage[]

export type setup = Collections['setup']['schema']['_output']
export declare const setup: setup[]

export type configuration = Collections['configuration']['schema']['_output']
export declare const configuration: configuration[]

export type userManagement = Collections['userManagement']['schema']['_output']
export declare const userManagement: userManagement[]

export type features = Collections['features']['schema']['_output']
export declare const features: features[]

export type guides = Collections['guides']['schema']['_output']
export declare const guides: guides[]

export type development = Collections['development']['schema']['_output']
export declare const development: development[]

export type templates = Collections['templates']['schema']['_output']
export declare const templates: templates[]
