<script lang="ts">
	import * as Table from '$lib/components/ui/table/index.js';
	import { Window } from '$lib/components/ui/window/index.js';

	const agentEnvConfig = [
		{
			name: 'AGENT_ID',
			defaultValue: '<hostname-of-your-server>',
			description: 'Hostname of the Arcane server'
		},
		{
			name: 'AGENT_LISTEN_ADDRESS',
			defaultValue: '0.0.0.0',
			description: 'The address to bind to on the agent host'
		},
		{
			name: 'AGENT_PORT',
			defaultValue: '3552',
			description: 'The Port for the agent to listen on'
		},
		{
			name: 'API_KEY',
			defaultValue: '-',
			description: 'The API Key generated by the Arcane Server'
		}
	];
</script>

<Window>
	<Table.Root class="mb-8">
		<Table.Caption>Agent environment variables and their usage.</Table.Caption>
		<Table.Header>
			<Table.Row>
				<Table.Head class="w-[220px]">Environment Variable</Table.Head>
				<Table.Head>Default Value</Table.Head>
				<Table.Head>Description</Table.Head>
			</Table.Row>
		</Table.Header>
		<Table.Body>
			{#each agentEnvConfig as env}
				<Table.Row>
					<Table.Cell class="font-medium">
						<code class="bg-muted rounded px-1 py-0.5">{env.name}</code>
					</Table.Cell>
					<Table.Cell>
						<code class="bg-muted rounded px-1 py-0.5">{env.defaultValue}</code>
					</Table.Cell>
					<Table.Cell>{env.description}</Table.Cell>
				</Table.Row>
			{/each}
		</Table.Body>
	</Table.Root>
</Window>
