<script lang="ts">
	import * as Table from '$lib/components/ui/table/index.js';

	const agentEnvConfig = [
		{
			name: 'AGENT_ID',
			defaultValue: '<hostname-of-your-server>',
			exampleValue: 'my-docker-host',
			description: 'Hostname of the Arcane server'
		},
		{
			name: 'AGENT_LISTEN_ADDRESS',
			defaultValue: '0.0.0.0',
			exampleValue: '',
			description: 'The address to bind to on the agent host'
		},
		{
			name: 'AGENT_PORT',
			defaultValue: '3552',
			exampleValue: '8080',
			description: 'The Port for the agent to listen on'
		},
		{
			name: 'API_KEY',
			defaultValue: '',
			exampleValue: 'your-api-key',
			description: 'The API Key generated by the Arcane Server'
		}
	];
</script>

<div class="env-var-table mt-4">
	<Table.Root class="mb-8">
		<Table.Caption>Agent environment variables and their usage.</Table.Caption>
		<Table.Header>
			<Table.Row>
				<Table.Head class="w-[220px]">Variable</Table.Head>
				<Table.Head>Description</Table.Head>
				<Table.Head>Value</Table.Head>
			</Table.Row>
		</Table.Header>
		<Table.Body>
			{#each agentEnvConfig as env}
				<Table.Row>
					<Table.Cell class="font-medium">
						<code class="rounded bg-muted px-1 py-0.5">{env.name}</code>
					</Table.Cell>
					<Table.Cell>{env.description}</Table.Cell>
					<Table.Cell>
						<div class="flex flex-col gap-1">
							<div class="flex items-center gap-1">
								<span class="w-14 text-xs text-muted-foreground">Default:</span>
								<code class="rounded bg-muted px-1 py-0.5">{env.defaultValue || '—'}</code>
							</div>
							<div class="flex items-center gap-1">
								<span class="w-14 text-xs text-muted-foreground">Example:</span>
								<code class="rounded bg-muted px-1 py-0.5">{env.exampleValue || '—'}</code>
							</div>
						</div>
					</Table.Cell>
				</Table.Row>
			{/each}
		</Table.Body>
	</Table.Root>
</div>
